### ISSUE TITLE
Configuring the max memory policy

### ISSUE THREAD

**Issue by davissp14** [fly-apps/redis#5]
To help mitigate OOM'ing the VM, we should by default configure a `max_memory` policy.

Things to consider when setting max memory:

**Persistence**
Redis needs to fork() when dumping to disk for RDB and when rewriting the AOF.  So we will need to reserve a percentage of the VM's allocated memory to account for CoW. 

**Evictions**
Key evictions happen when `memory_usage` _exceeds_ the `max_memory` policy.  So regardless of whether persistence is enabled or not, we still need some buffer room to work with between the `max_memory` policy specified and the total memory allocated to the VM.

**Additional processes running within the VM**
The metrics exporter, health checks, and any other processes that run within the same VM will need to be carefully evaluated to ensure we don't inadvertently trigger an OOM.

**Comment by jsierles** [comment]
Now we've set max memory (to the VM total), should we add a buffer? We also discussed adding swap to help here.

**Comment by davissp14** [comment]
Looks like you've already set a 10% buffer with the following:  https://github.com/fly-apps/redis/blob/1c9f4187b50a8639a103995bbef34ccc2b92d912/start-redis-server.sh#L6

I think we should probably aim to do our initial testing without SWAP and see if it's something we could potentially avoid.  If we do end up enabling swap, there's some kernel-level tuning we'd want to do.

**Comment by jsierles** [comment]
Are we comfortable with the current setting?

**Comment by jsierles** [comment]
Closing this for now since we have a configurable LRU cache now as well.
