### ISSUE TITLE
Can't use bind mount

### ISSUE THREAD

**Issue by rupurt** [fly-apps/redis#8]
Commit 3f51e801dafc3845ec72cda578cbe4e8774882e0 set the `WORKDIR` to `/` `"to prevent files from being overwritten in /data"`.

This unfortunately means that I can't use a bind mount locally in `docker-compose` with this image. I have to use a separate redis image in development which isn't ideal given I'm trying to replicate environments as closely as possible.

**Comment by jsierles** [comment]
Thanks for the report. I'm not sure why this would prevent bind mounts. Do you know?

**Comment by jsierles** [comment]
This should be fixed in the latest release. It removed the prometheus exporter.
